[2025-03-11T10:26:03.106+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-11T10:26:03.906+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_category_analysis.validate_orders manual__2025-03-11T10:25:41.084956+00:00 [queued]>
[2025-03-11T10:26:03.981+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_category_analysis.validate_orders manual__2025-03-11T10:25:41.084956+00:00 [queued]>
[2025-03-11T10:26:03.996+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-11T10:26:04.319+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): validate_orders> on 2025-03-11 10:25:41.084956+00:00
[2025-03-11T10:26:04.362+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=9172) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-11T10:26:04.378+0000] {standard_task_runner.py:72} INFO - Started process 9179 to run task
[2025-03-11T10:26:04.370+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weekly_category_analysis', 'validate_orders', 'manual__2025-03-11T10:25:41.084956+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/scheduled.py', '--cfg-path', '/tmp/tmpf308kjf9']
[2025-03-11T10:26:04.409+0000] {standard_task_runner.py:105} INFO - Job 270: Subtask validate_orders
[2025-03-11T10:26:04.768+0000] {task_command.py:467} INFO - Running <TaskInstance: weekly_category_analysis.validate_orders manual__2025-03-11T10:25:41.084956+00:00 [running]> on host efacfdd0be48
[2025-03-11T10:26:05.299+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_category_analysis' AIRFLOW_CTX_TASK_ID='validate_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T10:25:41.084956+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T10:25:41.084956+00:00'
[2025-03-11T10:26:05.311+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-11T10:26:05.315+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-11T10:26:05.317+0000] {logging_mixin.py:190} INFO - Current task name:validate_orders state:running start_date:2025-03-11 10:26:03.910001+00:00
[2025-03-11T10:26:05.319+0000] {logging_mixin.py:190} INFO - Dag name:weekly_category_analysis and current dag run status:running
[2025-03-11T10:26:05.323+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-11T10:26:05.442+0000] {logging_mixin.py:190} INFO - Validation successful. Found 1615 order records.
[2025-03-11T10:26:05.444+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-11T10:26:05.512+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-11T10:26:05.523+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weekly_category_analysis, task_id=validate_orders, run_id=manual__2025-03-11T10:25:41.084956+00:00, execution_date=20250311T102541, start_date=20250311T102603, end_date=20250311T102605
[2025-03-11T10:26:05.741+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-11T10:26:05.748+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-11T10:26:05.749+0000] {logging_mixin.py:190} INFO - Dag name:weekly_category_analysis queued_at:2025-03-11 10:25:41.129480+00:00
[2025-03-11T10:26:05.750+0000] {logging_mixin.py:190} INFO - Task hostname:efacfdd0be48 operator:PythonOperator
[2025-03-11T10:26:05.853+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-11T10:26:06.080+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-11T10:26:06.103+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
