[2025-03-11T05:32:58.427+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-11T05:32:59.071+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: validate_all_tables.customers scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-03-11T05:32:59.269+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: validate_all_tables.customers scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-03-11T05:32:59.296+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-11T05:32:59.476+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): customers> on 2025-03-10 00:00:00+00:00
[2025-03-11T05:32:59.574+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'validate_all_tables', 'customers', 'scheduled__2025-03-10T00:00:00+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/validate_all_tables_dag.py', '--cfg-path', '/tmp/tmpdpty59gd']
[2025-03-11T05:32:59.574+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=6055) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-11T05:32:59.592+0000] {standard_task_runner.py:105} INFO - Job 184: Subtask customers
[2025-03-11T05:32:59.600+0000] {standard_task_runner.py:72} INFO - Started process 6066 to run task
[2025-03-11T05:33:01.173+0000] {task_command.py:467} INFO - Running <TaskInstance: validate_all_tables.customers scheduled__2025-03-10T00:00:00+00:00 [running]> on host efacfdd0be48
[2025-03-11T05:33:01.884+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='validate_all_tables' AIRFLOW_CTX_TASK_ID='customers' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T00:00:00+00:00'
[2025-03-11T05:33:01.888+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-11T05:33:01.889+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-11T05:33:01.891+0000] {logging_mixin.py:190} INFO - Current task name:customers state:running start_date:2025-03-11 05:32:59.102453+00:00
[2025-03-11T05:33:01.892+0000] {logging_mixin.py:190} INFO - Dag name:validate_all_tables and current dag run status:running
[2025-03-11T05:33:01.893+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-11T05:33:03.296+0000] {logging_mixin.py:190} INFO - Customers validation and cleaning successful
[2025-03-11T05:33:03.311+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-11T05:33:03.371+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-11T05:33:03.376+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=validate_all_tables, task_id=customers, run_id=scheduled__2025-03-10T00:00:00+00:00, execution_date=20250310T000000, start_date=20250311T053259, end_date=20250311T053303
[2025-03-11T05:33:03.703+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-11T05:33:03.762+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-11T05:33:03.792+0000] {logging_mixin.py:190} INFO - Dag name:validate_all_tables queued_at:2025-03-11 05:32:28.924108+00:00
[2025-03-11T05:33:03.826+0000] {logging_mixin.py:190} INFO - Task hostname:efacfdd0be48 operator:PythonOperator
[2025-03-11T05:33:03.902+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-11T05:33:04.160+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-11T05:33:04.194+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
