[2025-03-12T15:05:23.671+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T15:05:23.857+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_category_analysis.customers scheduled__2025-03-05T13:00:00+00:00 [queued]>
[2025-03-12T15:05:23.988+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_category_analysis.customers scheduled__2025-03-05T13:00:00+00:00 [queued]>
[2025-03-12T15:05:23.999+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-12T15:05:24.176+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): customers> on 2025-03-05 13:00:00+00:00
[2025-03-12T15:05:24.246+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weekly_category_analysis', 'customers', 'scheduled__2025-03-05T13:00:00+00:00', '--job-id', '478', '--raw', '--subdir', 'DAGS_FOLDER/s3_data.py', '--cfg-path', '/tmp/tmpgc2ye63t']
[2025-03-12T15:05:24.301+0000] {standard_task_runner.py:105} INFO - Job 478: Subtask customers
[2025-03-12T15:05:24.242+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1281) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-12T15:05:24.320+0000] {standard_task_runner.py:72} INFO - Started process 1294 to run task
[2025-03-12T15:05:24.863+0000] {task_command.py:467} INFO - Running <TaskInstance: weekly_category_analysis.customers scheduled__2025-03-05T13:00:00+00:00 [running]> on host b404e9833d11
[2025-03-12T15:05:25.557+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_category_analysis' AIRFLOW_CTX_TASK_ID='customers' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-05T13:00:00+00:00'
[2025-03-12T15:05:25.606+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-12T15:05:25.607+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-12T15:05:25.608+0000] {logging_mixin.py:190} INFO - Current task name:customers state:running start_date:2025-03-12 15:05:23.884686+00:00
[2025-03-12T15:05:25.609+0000] {logging_mixin.py:190} INFO - Dag name:weekly_category_analysis and current dag run status:running
[2025-03-12T15:05:25.622+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T15:05:28.925+0000] {httpchecksum.py:481} INFO - Skipping checksum validation. Response did not contain one of the following algorithms: ['crc32', 'sha1', 'sha256'].
[2025-03-12T15:05:32.726+0000] {logging_mixin.py:190} INFO - Validation successful. Found 1445 customer records.
[2025-03-12T15:05:32.728+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-12T15:05:32.765+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T15:05:32.767+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weekly_category_analysis, task_id=customers, run_id=scheduled__2025-03-05T13:00:00+00:00, execution_date=20250305T130000, start_date=20250312T150523, end_date=20250312T150532
[2025-03-12T15:05:32.892+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-12T15:05:32.903+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-12T15:05:32.922+0000] {logging_mixin.py:190} INFO - Dag name:weekly_category_analysis queued_at:2025-03-12 15:04:59.119982+00:00
[2025-03-12T15:05:32.923+0000] {logging_mixin.py:190} INFO - Task hostname:b404e9833d11 operator:PythonOperator
[2025-03-12T15:05:32.973+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-12T15:05:33.108+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-12T15:05:33.120+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
