[2025-03-11T09:20:30.253+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-11T09:20:30.456+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: validate_all_tables.orders manual__2025-03-11T09:20:02.234928+00:00 [queued]>
[2025-03-11T09:20:30.570+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: validate_all_tables.orders manual__2025-03-11T09:20:02.234928+00:00 [queued]>
[2025-03-11T09:20:30.575+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-11T09:20:30.696+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): orders> on 2025-03-11 09:20:02.234928+00:00
[2025-03-11T09:20:30.741+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'validate_all_tables', 'orders', 'manual__2025-03-11T09:20:02.234928+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/validate_all_tables_dag.py', '--cfg-path', '/tmp/tmpp9461b_u']
[2025-03-11T09:20:30.730+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=8387) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-11T09:20:30.763+0000] {standard_task_runner.py:72} INFO - Started process 8393 to run task
[2025-03-11T09:20:30.761+0000] {standard_task_runner.py:105} INFO - Job 245: Subtask orders
[2025-03-11T09:20:31.291+0000] {task_command.py:467} INFO - Running <TaskInstance: validate_all_tables.orders manual__2025-03-11T09:20:02.234928+00:00 [running]> on host efacfdd0be48
[2025-03-11T09:20:32.954+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='validate_all_tables' AIRFLOW_CTX_TASK_ID='orders' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T09:20:02.234928+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T09:20:02.234928+00:00'
[2025-03-11T09:20:32.959+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-11T09:20:32.967+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-11T09:20:32.970+0000] {logging_mixin.py:190} INFO - Current task name:orders state:running start_date:2025-03-11 09:20:30.459481+00:00
[2025-03-11T09:20:32.971+0000] {logging_mixin.py:190} INFO - Dag name:validate_all_tables and current dag run status:running
[2025-03-11T09:20:32.986+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-11T09:20:33.032+0000] {logging_mixin.py:190} INFO - Validation successful. Found 1615 order records.
[2025-03-11T09:20:33.036+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-11T09:20:33.119+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-11T09:20:33.122+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=validate_all_tables, task_id=orders, run_id=manual__2025-03-11T09:20:02.234928+00:00, execution_date=20250311T092002, start_date=20250311T092030, end_date=20250311T092033
[2025-03-11T09:20:33.271+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-11T09:20:33.279+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-11T09:20:33.280+0000] {logging_mixin.py:190} INFO - Dag name:validate_all_tables queued_at:2025-03-11 09:20:02.394817+00:00
[2025-03-11T09:20:33.282+0000] {logging_mixin.py:190} INFO - Task hostname:efacfdd0be48 operator:PythonOperator
[2025-03-11T09:20:33.386+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-11T09:20:33.558+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-11T09:20:33.574+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
