[2025-03-12T15:05:40.171+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T15:05:40.244+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_category_analysis.orders scheduled__2025-03-05T13:00:00+00:00 [queued]>
[2025-03-12T15:05:40.305+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_category_analysis.orders scheduled__2025-03-05T13:00:00+00:00 [queued]>
[2025-03-12T15:05:40.306+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-12T15:05:40.359+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): orders> on 2025-03-05 13:00:00+00:00
[2025-03-12T15:05:40.373+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1316) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-12T15:05:40.377+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weekly_category_analysis', 'orders', 'scheduled__2025-03-05T13:00:00+00:00', '--job-id', '489', '--raw', '--subdir', 'DAGS_FOLDER/s3_data.py', '--cfg-path', '/tmp/tmpyde144h5']
[2025-03-12T15:05:40.377+0000] {standard_task_runner.py:72} INFO - Started process 1328 to run task
[2025-03-12T15:05:40.379+0000] {standard_task_runner.py:105} INFO - Job 489: Subtask orders
[2025-03-12T15:05:40.506+0000] {task_command.py:467} INFO - Running <TaskInstance: weekly_category_analysis.orders scheduled__2025-03-05T13:00:00+00:00 [running]> on host b404e9833d11
[2025-03-12T15:05:40.744+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_category_analysis' AIRFLOW_CTX_TASK_ID='orders' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-05T13:00:00+00:00'
[2025-03-12T15:05:40.758+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-12T15:05:40.760+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-12T15:05:40.763+0000] {logging_mixin.py:190} INFO - Current task name:orders state:running start_date:2025-03-12 15:05:40.253847+00:00
[2025-03-12T15:05:40.764+0000] {logging_mixin.py:190} INFO - Dag name:weekly_category_analysis and current dag run status:running
[2025-03-12T15:05:40.765+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T15:05:41.803+0000] {httpchecksum.py:481} INFO - Skipping checksum validation. Response did not contain one of the following algorithms: ['crc32', 'sha1', 'sha256'].
[2025-03-12T15:05:42.438+0000] {logging_mixin.py:190} INFO - Validation successful. Found 1615 order records.
[2025-03-12T15:05:42.439+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-12T15:05:42.461+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T15:05:42.463+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weekly_category_analysis, task_id=orders, run_id=scheduled__2025-03-05T13:00:00+00:00, execution_date=20250305T130000, start_date=20250312T150540, end_date=20250312T150542
[2025-03-12T15:05:42.587+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-12T15:05:42.590+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-12T15:05:42.591+0000] {logging_mixin.py:190} INFO - Dag name:weekly_category_analysis queued_at:2025-03-12 15:04:59.119982+00:00
[2025-03-12T15:05:42.592+0000] {logging_mixin.py:190} INFO - Task hostname:b404e9833d11 operator:PythonOperator
[2025-03-12T15:05:42.631+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-12T15:05:42.715+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-12T15:05:42.719+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
